name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y podman make

    - name: Build binary
      env:
        CGO_ENABLED: 0
        VERSION: dev-${{ github.sha }}
      run: |
        make linux-amd64

    - name: Test binary
      run: |
        binary_path=$(find output -name "korn_*" | head -1)
        chmod +x "$binary_path"
        "$binary_path" --version || echo "Binary built successfully"
        ls -lh "$binary_path"

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: korn-binary
        path: output/korn_*
