---
name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman make

      - name: Build binary
        env:
          CGO_ENABLED: 0
          VERSION: dev-${{ github.sha }}
        run: |
          make linux-amd64

      - name: Test binary
        run: |
          # Find the built binary (linux_amd64 pattern)
          binary_path=$(find output -name "korn_*_linux_amd64" | head -1)
          if [ -n "$binary_path" ]; then
            chmod +x "$binary_path"
            ls -lh "$binary_path"
            echo "✅ Binary built successfully: $binary_path"
            "$binary_path" --version || echo "Version check completed"
          else
            echo "❌ Error: Binary not found for linux-amd64"
            echo "Available files in output/:"
            ls -la output/
            exit 1
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: korn-binary
          path: output/korn_*
