name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman make

      - name: Get version from git tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build binary
        env:
          CGO_ENABLED: 0
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          make linux-amd64
          mkdir -p dist

      - name: Prepare release binary
        run: |
          # Find the built binary and copy it for release
          BINARY_FILE=$(find output -name "korn_*" | head -1)
          if [ -n "$BINARY_FILE" ]; then
            cp "$BINARY_FILE" "dist/korn-${{ steps.version.outputs.version }}"
            ls -lh "dist/korn-${{ steps.version.outputs.version }}"
          else
            echo "Error: Binary file not found"
            ls -la output/
            exit 1
          fi

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: dist/korn-${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

