---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman make

      - name: Get version from git tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build binary
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          make linux-${{ matrix.arch }}
          mkdir -p dist

      - name: Prepare release binary
        run: |
          # Find the built binary and copy it for release
          VERSION="${{ steps.version.outputs.version }}"
          PATTERN="korn_${VERSION}_linux_${{ matrix.arch }}"
          BINARY_FILE=$(find output -name "$PATTERN" | head -1)
          if [ -n "$BINARY_FILE" ]; then
            cp "$BINARY_FILE" \
              "dist/korn-${VERSION}-linux-${{ matrix.arch }}"
            ls -lh "dist/korn-${VERSION}-linux-${{ matrix.arch }}"
            echo "✅ Binary prepared: $BINARY_FILE"
          else
            echo "❌ Error: Binary file not found for pattern: $PATTERN"
            echo "Available files in output/:"
            ls -la output/
            exit 1
          fi

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: >
            dist/korn-${{ steps.version.outputs.version }}-linux-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
